tweaks
Signed-off-by: Joel Savitz <jsavitz@redhat.com>

diff --git a/dev/bmu b/dev/bmu
--- a/dev/bmu
+++ b/dev/bmu
@@ -358,7 +358,7 @@ run_go() {
 				# write "yes" to HOST_HAS_$target on success
 				printf -v ${config} "yes" > /dev/null
 			else
-				echo "failed to reach install target $tareget"
+				echo "failed to reach install target $target"
 			fi 
 		fi
 	done
@@ -435,12 +435,11 @@ run_console() {
 			printf "."
 		done
 		echo
-		console -M "console.eng.bos.redhat.com" "${HOST}"
-		# if console -M "${HOST}"; then
-		# 	D "disconnected: return of zero\n"
-		# else
-		# 	D "disconnected: return $?\n"
-		# fi
+		if console -M "console.eng.bos.redhat.com" "${HOST}"; then
+			D "disconnected: return of zero\n"
+		else
+			D "disconnected: return $?\n"
+		fi
 		reset
 		printf "disconnected. restarting"
 		for ((i=0;i<10;++i)); do
